---
title: "Mapping"
output: html_document
date: "2023-01-16"
editor_options: 
  chunk_output_type: console
---


```{r}
library(tidyverse)
library(sf)
library(ggplot2)
library(stringr)
library(osmdata)
data_folder <- "./data"
```

# PLot all Lads xoloured by collection type

```{r}
all_lad_codes_blue_green <- list.files(file.path(data_folder, "low_use_LAD_files")) %>%
  str_extract(.,"[\\S]+$") %>% str_remove(., ".csv")

all_lad_codes_bourne <- list.files(file.path(data_folder, "low_use_LAD_files_bourne")) %>%
  str_extract(.,"[\\S]+$") %>% str_remove(., ".csv")

all_lad_codes_scotland <- list.files(file.path(data_folder, "scotland")) %>%
  str_extract(.,"[\\S]+$") %>% str_remove(., ".csv")

LAD_sf <- read_sf(file.path(data_folder, "LAD_shapefiles")) %>%
  mutate(type = case_when(
    LAD22CD %in% all_lad_codes_blue_green ~"BG towns",
    LAD22CD %in% all_lad_codes_bourne ~"Bourne 2019",
    str_sub(LAD22CD, 1, 1)=="S" ~ "ScotGov",
    TRUE ~ "No Data"
  )) %>%
  filter( str_sub(LAD22CD, 1, 1)!="N" )
```


```{r}
table(LAD_sf$type)


```


```{r}

ggplot() +
  geom_sf(data = LAD_sf, mapping = aes(fill = type, linetype = NA)) + 
  coord_sf() +
  ggtitle("Data available for project by collection type")


```


# PLot LSOA data

DO not try to plot the whole of the UK it would be horrible
```{r}

```


```{r}


"East Riding of Yorkshire E06000011.csv"

LSOA_sf <- bind_rows(read_sf(file.path(data_folder, "LSOA_(Dec_2011)_Boundaries_Generalised_Clipped_(BGC)_EW_V3")) %>%
  select(LSOA11CD),
  read_sf(file.path(data_folder, "SG_DataZoneBdry_2011")) %>%
  select(LSOA11CD = DataZone)
  ) %>%
  left_join(read_rds(file.path(data_folder, "lsoa_to_all_lookup.rds")), by = c("LSOA11CD"="lsoa11cd"))





file_path <- file.path(data_folder, "low_use_LAD_files_bourne/Cornwall E06000052.csv")




#If the shape file is merged onto the tibble it no longer counts as a geometric object.

#that is why the merging is done onto the shape file

single_lad  = LSOA_sf %>% inner_join(read_csv(file_path), by = c("LSOA11CD" = "lsoa11cd" )) %>%
  mutate(perc = low_use_ratio * 100)



```

```{r}
lads_to_map <- c( file.path(data_folder,'low_use_LAD_files','West Devon E07000047.csv'),
file.path(data_folder,'low_use_LAD_files_bourne','West Suffolk E07000245.csv'),
file.path(data_folder,'low_use_LAD_files_bourne','Conwy W06000003.csv'),
file.path(data_folder,'scotland','East Lothian S12000010.csv') )

lads_to_map %>% walk(~{

  temp <- read_csv(.x)
  single_lad  = LSOA_sf %>% 
    filter(Admin_district_code == unique(temp$Admin_district_code)[1]) %>%
    left_join(temp, by = c("LSOA11CD" = "lsoa11cd" )) %>%
  mutate(
    low_use = ifelse(is.na(low_use), 0, low_use),
    low_use_ratio = ifelse(is.na(low_use_ratio), 0, low_use_ratio),
    perc = low_use_ratio * 100)

LADNM <- basename(.x) %>% str_remove(., "\\s\\w\\d.*")
plot_title <- paste("Low use properties as a percent of LSOA in", LADNM)

ggplot() +
  geom_sf(data = single_lad, mapping = aes(fill = perc)) + 
  coord_sf() +
  scale_fill_viridis_b() +
  ggtitle(plot_title)

ggsave(file.path(data_folder, 'maps', paste(basename(.x) %>% str_replace(., ".csv", ".pdf"))))

})
```


South Devon, East Suffolk, Conwy, East Lothian


```{r}

tucson_major <- getbb(place_name = "cornwall") %>%
  opq(timeout = 50) %>%
  add_osm_feature(key = "highway", 
                  value = c("motorway", "primary", "secondary")) %>%
  osmdata_sf()


street_plot <- ggplot() +
  geom_sf(data = tucson_major$osm_lines,
          inherit.aes = FALSE,
          color = "black",
          size = 0.2)
# Print the plot
street_plot


tucson_minor <- getbb(place_name = "Cornwall") %>%
  opq() %>%
  add_osm_feature(key = "highway", value = c("tertiary", "residential")) %>%
  osmdata_sf()

street_plot <- street_plot +
  geom_sf(data = tucson_minor$osm_lines,
          inherit.aes = FALSE,
          color = "#666666",  # medium gray
          size = 0.1) # half the width of the major roads
# Print the plot
street_plot

ggplot()+
      geom_sf(data = single_lad, mapping = aes(fill = perc,  linetype = NA)) + 
  coord_sf() +
  geom_sf(data = tucson_major$osm_lines,
          inherit.aes = FALSE,
          color = "orange",
          size = 0.2) +
  geom_sf(data = tucson_minor$osm_lines,
          inherit.aes = FALSE,
          color = "orange",
          size = 0.2) +
  scale_fill_viridis_b() +
  labs(title ="Low use properties as percent of MSOA in Cornwall", fill = "Percent")
```


```{r}



low_use_map_plot <- function(data_path, LSOA_sf,  title = "plot title"){
  
  ##
  ## Create a plot of the named lad using the file path
  ## depends on ggplot2, sf, osmdata, tidyverse
  ##
  
  #If the shape file is merged onto the tibble it no longer counts as a geometric object.
#that is why the merging is done onto the shape file
single_lad  = LSOA_sf %>% inner_join(read_csv(data_path), by = c("LSOA11CD" = "lsoa11cd" )) %>%
  mutate(perc = low_use_ratio * 100) %>%
  #convert to correct coordinate sytem
  st_transform(., 4326)

#get bounding box for LAD
lad_bbox <- st_bbox(single_lad)

LAD_major <- lad_bbox %>%
  opq(timeout = 50) %>%
  add_osm_feature(key = "highway", 
                  value = c("motorway", "primary", "secondary")) %>%
  osmdata_sf()

LAD_minor <- lad_bbox %>%
  opq(timeout = 50) %>%
  add_osm_feature(key = "highway", value = c("tertiary", "residential")) %>%
  osmdata_sf()

out <- ggplot()+
      geom_sf(data = single_lad, mapping = aes(fill = perc,  linetype = NA)) + 
  coord_sf() +
  geom_sf(data = LAD_major$osm_lines,
          inherit.aes = FALSE,
          color = "orange",
          size = 0.2) +
  geom_sf(data = LAD_minor$osm_lines,
          inherit.aes = FALSE,
          color = "orange",
          size = 0.2) +
  scale_fill_viridis_b() +
  labs(title = title, fill = "Percent")

return(out)
  
}

```



```{r}
g <- low_use_map_plot(data_path = file.path(data_folder, "low_use_LAD_files_bourne", "Cornwall E06000052.csv"), 
                 LSOA_sf,  title = "Low use properties as percent of MSOA in Cornwall" )

g


g2 <- low_use_map_plot(data_path = file.path(data_folder, "low_use_LAD_files", "East Riding of Yorkshire E06000011.csv"), 
                 LSOA_sf,  title = "Low use properties as percent of MSOA in East Riding" )

g2
```

